#pragma kernel UploadGlyphs

uniform ByteAddressBuffer _src;
uniform RWByteAddressBuffer _dst;
uniform ByteAddressBuffer _meta;

uint _startOffset;

[numthreads(64, 1, 1)]
void UploadGlyphs(uint threadId : SV_GroupIndex, uint3 groupIds : SV_GroupID)
{
    uint3 m = _meta.Load3((groupIds.x + _startOffset) * 12);

    uint srcBase = m.x;
    uint dstBase = m.y;
    uint elementCount = m.z;

    for (uint i = threadId; i < elementCount; i += 64)
    {
        uint src = (srcBase + i) * 128;
        uint dst = (dstBase + i) * 128;
        _dst.Store4(dst,       _src.Load4(src));
        _dst.Store4(dst + 16,  _src.Load4(src + 16));
        _dst.Store4(dst + 32,  _src.Load4(src + 32));
        _dst.Store4(dst + 48,  _src.Load4(src + 48));
        _dst.Store4(dst + 64,  _src.Load4(src + 64));
        _dst.Store4(dst + 80,  _src.Load4(src + 80));
        _dst.Store4(dst + 96,  _src.Load4(src + 96));
        _dst.Store4(dst + 112, _src.Load4(src + 112));
        //can also just do (float) cast in vertex shader (instead of "asflaot" to avoid this complexity?
        //uint4 lastLoad = _src.Load4(src + 112);
        //float arrayIndex = (float) lastLoad.x;
        //lastLoad.x = asuint(arrayIndex);
        //_dst.Store4(dst + 112, lastLoad);
    }
}